### ISSUE TITLE
issues in finding successors

### ISSUE THREAD

**Issue by zhouhq10** [tswsxk/XKT#2]
Hi, thanks for the great work. 
I was wondering if the code in https://github.com/tswsxk/XKT/blob/24ae94e7accd71c9b107ed2435387687701d92ae/XKT/SKT/utils.py#L99 has a typo, where the function should return the successors rather than neighbors?

**Comment by zhouhq10** [comment]
Meanwhile, are you planning to open-source the same data you use in the paper? I found Assistment 2009-2010 in your codes and websites, while the results in paper are from Assistment 2015. Thanks a lot in advance!

**Comment by tswsxk** [comment]
Hi, the typo does exist in this reorgnized code, which has been fixed now, thx.

**Comment by tswsxk** [comment]
The data has been already published in another open repo named as [EduData](https://github.com/bigdata-ustc/EduData)
